### ISSUE TITLE
Upload Form Dropdown options - All modules

### ISSUE THREAD

**Issue by toniolsen** [helendallas/FRC_FBIS#26]
@helendallas @jeremyshelton @philipfrenzel 

Here is a spreadsheet of all the current dropdown options for the upload forms for all three modules:
These will all need to be made the same even if some don't apply to the module, i.e. curation process. We can just grey out those options.

[Forms Dropdown options.xlsx](https://github.com/helendallas/FRC_FBIS/files/3641850/Forms.Dropdown.options.xlsx)

**Comment by jeremyshelton** [comment]
Thanks @toniolsen - super useful!

My thoughts: 

**Specific biotope**
I reckon we work toward a universal list of specific biotopes, so the same dropdown options in all three modules (it is fine to have them for the fish too, so long as they are not compulsory). I think @helendallas is going to take this on? 

**Sampling effort**
You can include the replicates option for fish. 

**Abundance**
We should include Number, Percentage Abundance and Density options for all three modules. 

So, the only dropdown that vary among modules will be Broad Biotope and Sampling Method, and then the additional category 'Curation process' for Algae. 

Thoughts @helendallas @philipfrenzel?

**Comment by toniolsen** [comment]
Thanks @jeremyshelton.
I have made the changes on the Dropbox version.
[Forms Dropdown options.xlsx](https://github.com/helendallas/FRC_FBIS/files/3646047/Forms.Dropdown.options.xlsx)

**Comment by helendallas** [comment]
@toniolsen @jeremyshelton 
I have update file.  lines 3 to 70.

[Forms Dropdown options_Final 2019 09 30.xlsx](https://github.com/helendallas/FRC_FBIS/files/3670491/Forms.Dropdown.options_Final.2019.09.30.xlsx)

Made all words Proper, and sorted alphabetically.
Please add Kick **Net** not just Kick

@philipfrenzel I have deleted sampling from 
Soft Bottom
Vegetation

Please explain what : In situ sampling is.  I have not included for now.  Also deleted some specific and substratum categories that you had as they didnt make sense. 

Toni and Phil, please check all existing spreadsheets to make sure biotopes etc match existing final list so that they import correctly.

**Comment by toniolsen** [comment]
Thanks @helendallas 

I have made the changes to the existing fish and invertebrate species spreadsheets in both "Data to combine" folders on Dropbox.
@Janette-Lumley @Aneri16 if you capture anymore fish or invertebrate species data, please use one of the datasheets in the data to combine folder as a template so it retains the dropdown options. Thanks!

Once all these sheets have been combined for Kartoza to ingest, a meticulous, final check through the sheets would be worthwhile.

@helendallas @jeremyshelton

**Comment by helendallas** [comment]
thanks @toniolsen 

Agreed re final check of combined invertebrate taxon datafile.

**Comment by philipfrenzel** [comment]
Thanks @helendallas 

Justine had suggested calling the BenthoTorch sampling as 'In situ sampling' because the heading name was sample location. But BenthoTorch sampling is only used for Chl A biomass measurements (and not AFDM). I've updated the Excel to read 'In situ sampling (BenthoTorch)'. @jeremyshelton did you manage to check whether the link is still valid to the ticket? Or whether we need to upload the Excel again?

Agreed re final check @helendallas @toniolsen @jeremyshelton . Will definitely check that the biotope classifications match the data before final algae upload.

**Comment by helendallas** [comment]
@jeremyshelton 
Please confirm if this has been ticketed on the Kartoza Github, and that all is in order. SO that I can close this ticket.

@philipfrenzel 
I have created a new data template for inverts with our standardised biotopes. I suggest you revise existing template to reflect the final list and not rely on doing it at the end.

**Comment by philipfrenzel** [comment]
Good idea. I'll adapt accordingly @helendallas
