### ISSUE TITLE
Invertebrate Taxon Template - Master

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#55]
@Aneri16 @Janette-Lumley 

The final master template to use for all data capture is: Link below 

https://www.dropbox.com/s/szmdjeuj4lrpudo/Invertebrate%20Taxon%20Template%202019_10_03.xlsx?dl=0

**Invertebrate Taxon Template 2019_10_03.xlsx**

[Invertebrate Taxon Template 2019_10_03.xlsx](https://github.com/helendallas/FRC_FBIS/files/3695810/Invertebrate.Taxon.Template.2019_10_03.xlsx)

**Comment by helendallas** [comment]
@philipfrenzel 
Please revise the algal template so that it aligns with the invertebrate taxon template, specifically:

- Sampling Effort (new column)
- Abundance Measure (New Name with new dropdown)
- Abundance Value (instead of having separate columns for number/count and percentage abundance and density) , I have created Abundance Measure and Abundance Value
- Broad Biotope - check your biotopes match these
- Specific Biotope - check your biotopes match these
- Substratum - check your biotopes match these

![image](https://user-images.githubusercontent.com/45286876/66562405-e64f0380-eb5b-11e9-802c-29fad4b1b262.png)

**Comment by philipfrenzel** [comment]
Best to standardise, agreed. I will do so. This will take some time for the algae data - especially given that I have captured the algae data based on the original specific biotope dropdown options. I will trawl through the raw data sheets again so that I can differentiate between the specific biotopes based on this new classification. 

@helendallas
